name: Frontend chart
language: nodejs
variables:
  - name: bearer_token
    inputType: Secret
    description: ''
    defaultValue: dashboard_bearer_token
    required: false
  - name: chart_data_topic
    inputType: InputTopic
    description: ''
    defaultValue: chart-data
    required: true
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
