name: Frontend chart
language: nodejs
variables:
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: abc111
    required: false
  - name: chart_data_topic
    inputType: InputTopic
    description: ''
    defaultValue: chart_data
    required: true
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
