name: Frontend chart
language: nodejs
variables:
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: pat-884cd191640248ffa02ca08e9ca1a083
    required: false
  - name: chart_data_topic
    inputType: InputTopic
    description: ''
    defaultValue: chart-data
    required: true
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
